excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://bineetgh.github.io
title: One life to live!
email: bineetkmishra@gmail.com
author: Bineet Mishra
description: Try out everything possible or impossible, you have one life to live. 
paginate: 5
google_analytics: 